pip install streamlit
pip install pandas
pip install json 
pip install finplot 
pip install numpy 
pip install matplotlib.pyplot
pip install plotly.graph_objects 
pip install plotly.express 
pip install requests
streamlit run main.py